[project]
name = "my-fastapi-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    'fastapi',
    'uvicorn',
    'sqlalchemy',
    'pydantic',
    'httpx',
    'python-dotenv',
    'passlib',
    'bcrypt',
]
